// src/core/subscription/plans.ts
// Catálogo declarativo oficial de Planes (Free, Starter, Growth, Pro, Enterprise) y Addons

import { SubscriptionPlan, SubscriptionAddon, PlanId } from './types';

export const SUBSCRIPTION_PLANS: Record<PlanId, SubscriptionPlan> = {
  FREE: {
    id: 'FREE',
    name: 'Citiox Free',
    description: 'Plan de entrada freemium ideal para probar la plataforma y despegar tu negocio.',
    priceMonthly: 0,
    priceYearly: 0,
    badge: 'Gratis',
    limits: {
      transactions: 50,
      branches: 1,
      users: 1,
      employees: 1,
      customers: 100,
      products: 10,
      services: 5,
      resources: 5,
      storageMB: 100,
      whatsappMessages: 0,
      aiCredits: 0,
    },
    features: {
      promotions: 'none',
      communications: 'none',
      reports: 'basic',
      automations: 'none',
      ai: 'none',
      api: 'none',
      branding: 'citiox_watermark',
      customDomain: false,
      customTheme: true,
      rolesAndPermissions: 'none',
      auditLogs: false,
      sso: false,
    },
  },
  STARTER: {
    id: 'STARTER',
    name: 'Starter',
    description: 'Perfecto para pequeños negocios que buscan digitalizar su atención y servicios.',
    priceMonthly: 19,
    priceYearly: 190,
    limits: {
      transactions: 500,
      branches: 1,
      users: 2,
      employees: 3,
      customers: 500,
      products: 50,
      services: 20,
      resources: 15,
      storageMB: 1024,
      whatsappMessages: 100,
      aiCredits: 10,
    },
    features: {
      promotions: 'basic',
      communications: 'basic',
      reports: 'basic',
      automations: 'none',
      ai: 'none',
      api: 'none',
      branding: 'custom_logo',
      customDomain: false,
      customTheme: true,
      rolesAndPermissions: 'basic',
      auditLogs: false,
      sso: false,
    },
  },
  GROWTH: {
    id: 'GROWTH',
    name: 'Growth',
    description: 'Diseñado para negocios en expansión con múltiples canales, mesas, entregas y automatizaciones.',
    priceMonthly: 49,
    priceYearly: 490,
    isPopular: true,
    badge: 'Más Popular',
    limits: {
      transactions: 2000,
      branches: 5,
      users: 10,
      employees: 15,
      customers: 5000,
      products: 250,
      services: 100,
      resources: 50,
      storageMB: 5120,
      whatsappMessages: 1000,
      aiCredits: 100,
    },
    features: {
      promotions: 'advanced',
      communications: 'standard',
      reports: 'advanced',
      automations: 'standard',
      ai: 'basic',
      api: 'none',
      branding: 'custom_logo',
      customDomain: true,
      customTheme: true,
      rolesAndPermissions: 'standard',
      auditLogs: false,
      sso: false,
    },
  },
  PRO: {
    id: 'PRO',
    name: 'Pro',
    description: 'Potencia total para empresas consolidadas con asistentes de IA, API, Academia y fidelización.',
    priceMonthly: 99,
    priceYearly: 990,
    limits: {
      transactions: 999999,
      branches: 10,
      users: 25,
      employees: 50,
      customers: 50000,
      products: 1000,
      services: 500,
      resources: 200,
      storageMB: 25600,
      whatsappMessages: 5000,
      aiCredits: 1000,
    },
    features: {
      promotions: 'advanced',
      communications: 'advanced',
      reports: 'advanced',
      automations: 'advanced',
      ai: 'advanced',
      api: 'advanced',
      branding: 'white_label',
      customDomain: true,
      customTheme: true,
      rolesAndPermissions: 'advanced',
      auditLogs: true,
      sso: false,
    },
  },
  ENTERPRISE: {
    id: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'Solución corporativa multiempresa White Label con SSO, soporte prioritario e IA a medida.',
    priceMonthly: 249,
    priceYearly: 2490,
    limits: {
      transactions: 9999999,
      branches: 999,
      users: 999,
      employees: 999,
      customers: 9999999,
      products: 999999,
      services: 999999,
      resources: 999999,
      storageMB: 1048576,
      whatsappMessages: 50000,
      aiCredits: 10000,
    },
    features: {
      promotions: 'enterprise',
      communications: 'enterprise',
      reports: 'enterprise',
      automations: 'enterprise',
      ai: 'enterprise',
      api: 'enterprise',
      branding: 'white_label',
      customDomain: true,
      customTheme: true,
      rolesAndPermissions: 'enterprise',
      auditLogs: true,
      sso: true,
    },
  },
};

export const SUBSCRIPTION_ADDONS: Record<string, SubscriptionAddon> = {
  extra_branch: {
    id: 'extra_branch',
    name: 'Sucursal Adicional',
    description: 'Añade 1 sucursal operable extra a tu cuenta.',
    priceMonthly: 10,
    limitBonus: { branches: 1 },
  },
  extra_user: {
    id: 'extra_user',
    name: 'Usuario Administrativo Adicional',
    description: 'Permite agregar 1 usuario administrativo o cajero adicional.',
    priceMonthly: 5,
    limitBonus: { users: 1 },
  },
  extra_employee: {
    id: 'extra_employee',
    name: 'Profesional / Empleado Adicional',
    description: 'Añade 1 empleado o profesional adicional en agenda/turnos.',
    priceMonthly: 5,
    limitBonus: { employees: 1 },
  },
  extra_transactions: {
    id: 'extra_transactions',
    name: 'Pack +1,000 Transacciones',
    description: 'Amplía tu cupo en 1,000 transacciones (citas, pedidos, ventas) al mes.',
    priceMonthly: 15,
    limitBonus: { transactions: 1000 },
  },
  extra_whatsapp: {
    id: 'extra_whatsapp',
    name: 'Pack +1,000 Mensajes WhatsApp',
    description: 'Agrega 1,000 mensajes transaccionales por WhatsApp.',
    priceMonthly: 12,
    limitBonus: { whatsappMessages: 1000 },
  },
  extra_ai: {
    id: 'extra_ai',
    name: 'Pack +500 Créditos IA',
    description: 'Agrega 500 consultas o automatizaciones con Asistentes IA.',
    priceMonthly: 10,
    limitBonus: { aiCredits: 500 },
  },
  extra_storage: {
    id: 'extra_storage',
    name: 'Pack +10 GB Almacenamiento',
    description: 'Agrega 10,240 MB de espacio para multimedia y fotos de servicios.',
    priceMonthly: 8,
    limitBonus: { storageMB: 10240 },
  },
  api_access: {
    id: 'api_access',
    name: 'Acceso a API & Webhooks',
    description: 'Habilita claves API dedicadas para integrar sistemas externos.',
    priceMonthly: 25,
    limitBonus: {},
    featureAccessBonus: { api: 'advanced' },
  },
};
